baseURL = "//www.smokefreewaiheke.org.nz/"
languageCode = "en-us"
title = "SmokeFree Waiheke"
theme = "ananke"
# resourceDir = "../resources"

SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = "/images/smokefree-logo-og.jpg"
  description = "The last cigarette on the island. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-white"
  # featured_image = "/images/smoke-banner.jpg"
  recent_posts_number = 20